# .github/workflows/deploy.yml (예시)
name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # 필요한 JDK 버전
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Copy Jar to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ec2-user/apps/board/board"

      - name: Remote SSH and Restart Docker
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/apps
            docker compose -f /home/ec2-user/apps/docker-compose.yml down
            docker compose -f /home/ec2-user/apps/docker-compose.yml up -d